version: '3.4'

services:
  web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8000:8000"

  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8001:8001"

